server:
  port: 9920
spring:
  application:
    name: cloud-order
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.121.130:8080
        port: 8920
    nacos:
      discovery:
        server-addr: 192.168.121.130:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mymysql.skyln.cn:3306/order_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
# 控制台输出sql、下划线转驼峰
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#修改负载均衡策略为根据响应时间
#cloud-video:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule