#server:
#  port: 9900
#spring:
#  application:
#    name: cloud-video
#  redis:
#    host: 192.168.121.128
#    password: redisPWD
#    port: 6379
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 10
#        # 连接池中的最大空闲连接
#        max-idle: 10
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
#  zipkin:
#    base-url: http://192.168.121.130:9411/ #zipkin地址
#    discovery-client-enabled: false  #不用开启服务发现
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比
#  cloud:
#    sentinel:
#      transport:
#        dashboard: 192.168.121.130:8080
#        port: 8900
#    nacos:
#      discovery:
#        server-addr: 192.168.121.130:8848
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.121.130:3306/video_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
## 控制台输出sql、下划线转驼峰
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
##开启Feign对Sentinel的支持
#feign:
#  sentinel:
#    enabled: true